### ISSUE TITLE
No welcome message when new user sign up

### ISSUE THREAD

**Issue by alesanchezr** [refresh-miami/refresh-miami#1]
## Expected behavior

A welcome message with an explanation about what happens next, how do I engage in the online community and the different ways I can interact, what to expect and how to take advantage.

![Introduction –](https://user-images.githubusercontent.com/426452/123988608-27252680-d996-11eb-9acd-163b1e03861b.png)

## Steps to replicate

1. Fill the form to create a new account.
2. Press submit and wait for the default welcome message.

**Comment by dimensionmedia** [comment]
This might be us looking at the old refresh.miami website @alesanchezr ? See screenshot of what i arrive to when i fill out the register form to create a new account on mymiami.tech. Likely this can be closed based on the steps to replicate you've given.

Related: message after account is activated:
https://github.com/refresh-miami/refresh-miami/issues/44

![Screen Shot 2021-07-21 at 10 58 38 AM](https://user-images.githubusercontent.com/721134/126510947-3c4efa19-280c-4372-b82a-53f1aed42b20.png)
