### ISSUE TITLE
As a Public user, a welcoming email is sent for new users to authenticate profile

### ISSUE THREAD

**Issue by phildesignsgfx** [refresh-miami/refresh-miami#12]
## User Story:
```
As a Public user, a welcoming email is sent for new users


```
## Acceptance Criteria:

Elaborate more on the story for specific expected behaviors, for example:

- A welcoming email is received once users sign up
- A brief message is sent to the user's inbox " Activate: " Plus the activation link"
- The welcoming email should include a paragraph to welcome users, as well as a link to guide the user to login to the site which is present on the site

**Comment by mariaderchi** [comment]
This has been fixed. We can close this ticket.
