### ISSUE TITLE
Missing Guidelines on each forum

### ISSUE THREAD

**Issue by allenstfort23** [refresh-miami/refresh-miami#17]
The first post for each forum should be a "guidelines" post

## Steps to replicate

1. Go to discussions
2. Click on one of the discussions
3. Look at the first post on the top (features).

## Expected behavior

- The guideline should be visible on the top.
- The guideline should stipulate the rules, code of conduct, and other important messages for anyone that would like to post in the forum.

**Comment by alesanchezr** [comment]
Yeah this is more for Maria than you.. when you open a forum is good practice that the first post is about rules and guidelines.

**Comment by lubryan1981** [comment]
completed.  WP Admin > buddy boss > forum > discussion post > "super sticky" > shows on all topics.  Only have to edit once.
