### ISSUE TITLE
As an anonymous user, when I click on "news" on the navbar I should see a page with recent news and a way to search and filter those news.

### ISSUE THREAD

**Issue by Kcuevas95** [refresh-miami/refresh-miami#19]
The current categories are off, and the current news in the list are not part of any of those two categories, the categories are mostly empty.

**Comment by dimensionmedia** [comment]
![Screen Shot 2021-07-21 at 11 09 35 AM](https://user-images.githubusercontent.com/721134/126512776-62d01c63-761d-4a5e-8974-6da9f092dfac.png)

This is a current screenshot of mymiami.tech. Brian approved the current search and filters. We won't be adding any more.

Moving on to what is on the page - everything appears to be working for me. Search works, at least how it's expected to work with WordPress. Category filters work - we just need to add more categories and posts with those categories. I believe Brian or Maria can do this on their own but I'm happy to remind.

If there's a specific issue, let's do a video or walkthrough to narrrow down the scope of this potential issue? Involve Maria.

**Comment by mariaderchi** [comment]
This is on my to-do list to add relevant categories to each article. Nothing for your to do here @dimensionmedia.
