### ISSUE TITLE
"Go to dashboard" after signup is to ambiguos

### ISSUE THREAD

**Issue by alesanchezr** [refresh-miami/refresh-miami#2]
**Describe the bug**
After you signup, there is a welcome message and "go to dashboard" button, instead of "going to the dashboard" we should tell the user more specific things he can do inside the community like: Writing an article, creating a job posting, etc.

**To Reproduce**
1. Fill the signup form
2. Submit the form
3. Wait for the welcome message

**Expected behavior**
A more explicit and friendly call to action with a few several options that I can do on the website.

**Comment by dimensionmedia** [comment]
This is a content issue (we should label tickets related to content and not tech issues). Can we ping Maria on these @alesanchezr - i'm having trouble doing that in the GH comments for some reason.

**Comment by mariaderchi** [comment]
Text has been updated to prompt users to check their emails.
