### ISSUE TITLE
As a registered user, I should receive a message to inform me that an activation email was sent to me.

### ISSUE THREAD

**Issue by gabo180** [refresh-miami/refresh-miami#20]
This is the current message that is being displayed, it should also say in a prominent highlighted way that I need to to check my indox for activation email:

![Screen Shot 2021-07-20 at 12 04 38 AM](https://user-images.githubusercontent.com/426452/126260277-3b70d042-5057-4efb-bbca-eae3ac46d602.png)

**Comment by dimensionmedia** [comment]
We should be getting an activation email - nicely formatted. I just got one this morning that I was bcc'd on. Looks like this. Can we confirm and close?

![Screen Shot 2021-07-20 at 4 56 08 AM](https://user-images.githubusercontent.com/721134/126292383-2f60d569-9a49-4554-a6e6-748a8a7594c1.png)

**Comment by alesanchezr** [comment]
Yes the email is nice, but it should say on the website that you need to check your inbox to find this email.

**Comment by dimensionmedia** [comment]
@alesanchezr that sounds ok with me. Maria (again I can't seem to tag her in GH like I can with you) should be able to update the activate email page herself. Can we maybe assign tickets to people so this makes it more clear (no invite yet, i have limited capabilities - basically just commenting on these tickets).

**Comment by mariaderchi** [comment]
@dimensionmedia  - Yes I can do this! Do you mind sending me the link to where this is? Is it under Forms --> Register Updated? I will start documenting where these places live so I can find them next time without bugging you.

**Comment by dimensionmedia** [comment]
@mariaderchi since i didn't write the copy, i assume you knew. I think it might be this: https://mymiami.tech/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=notification&id=11&nid=6098020ccd6d5

**Comment by mariaderchi** [comment]
I think we're talking about two different areas. You sent me a link to the confirmation email text. I'm specifically looking for where the text in the below screenshot lives:

<img width="1282" alt="Screen Shot 2021-07-27 at 12 04 17 AM" src="https://user-images.githubusercontent.com/87676431/127094164-6bedbee7-9f68-4a58-83e7-38ff1d62fe8f.png">

**Comment by dimensionmedia** [comment]
@mariaderchi i found this. try this? https://mymiami.tech/wp-admin/post.php?post=125167&action=edit

**Comment by mariaderchi** [comment]
That worked! I updated the text. Closing this ticket.
