### ISSUE TITLE
the discussion tab should have a dropdown tab to allow the user to quickly search their topic

### ISSUE THREAD

**Issue by allenstfort23** [refresh-miami/refresh-miami#22]
## User Story:
```
As a public user, the discussion tab should have a dropdown tab to allow the user to quickly search their topic.
```
## Acceptance Criteria:

Elaborate more on the story for specific expected behaviors, for example:

- A discussion dropdown tab should be added to allow users to quickly search what topic they are looking for or to have a dropdown tab with different categories of boards.

**Comment by alesanchezr** [comment]
this was moved and merged with #28
