### ISSUE TITLE
As a public user, I expect the Event page functionality to be more navigable.

### ISSUE THREAD

**Issue by marcoescmont** [refresh-miami/refresh-miami#24]
## User Story:
```
As a public user, when I'm growing events in the events section I can group the events on a monthly calendar when clicking on the "months" tab.
```
## Acceptance Criteria:

Specific expected behaviors, for example:
- Option to get to the next or previous month
- When you click ' + Export Events', you get all the info except the location of the event.

**Comment by lubryan1981** [comment]
there are currently two ways to access events in following or previous months. the Drop down Where it says "now onward" and also the list or month view toggle next to the search bar. Here is the loom: 
https://www.loom.com/share/86f268d777b04ca59b88e45085cb5693

**Comment by lubryan1981** [comment]
Many of the events did not have a location, which is why location was not coming through the export. But I encountered a different bug when adding a venue to an event. Will create separate ticket and close
