### ISSUE TITLE
The 'Connect Socially' link on the footer is hard to see

### ISSUE THREAD

**Issue by marcoescmont** [refresh-miami/refresh-miami#25]
- When you hoover the mouse over the icons the main icon should change to white so it can be visible.
![Connect Socially icons color problem](https://user-images.githubusercontent.com/81428361/124060002-127a7a00-d9fa-11eb-877a-3f2d92b69fad.png)

**Comment by dimensionmedia** [comment]
![Screen Shot 2021-07-21 at 12 08 52 PM](https://user-images.githubusercontent.com/721134/126522304-766f7ea6-4fd0-491a-9661-41457499e49f.png)
Resolved.
