### ISSUE TITLE
As a public user I should be able to see a navbar on the top of the website with shotcuts to the most important parts

### ISSUE THREAD

**Issue by alesanchezr** [refresh-miami/refresh-miami#28]
## User Story:
```
As a public user I should be able to see a navbar on the top of the website with shotcuts to the most important parts
```

## Acceptance Criteria:

As a public user I should be able to see a navbar on the top of the website with shotcuts to the most important parts

- 'Event' dropdown on the Navbar: There should be the options for 'List', 'Month' and 'Day' so you reduce steps to reach the desirable option.
-

**Comment by mariaderchi** [comment]
I like this idea if it's possible! But again - if we're limited on time/resources, let's put this in a future iteration and focus for launch on any major bugs.
