### ISSUE TITLE
I can't login with my email and password after email verification

### ISSUE THREAD

**Issue by alesanchezr** [refresh-miami/refresh-miami#29]
**Describe the bug**
I can't log in with my email and password after email verification, the system says "Invalid email and password". By the way, we can't remind passwords either, it seems that we are not really signed up.

**To Reproduce**
1. Create a new account
2. Check email and click on the verification link
3. Go back to the website and try to log in

**Expected behavior**
After verifying my account I should be able to log in.

- The following error occurs when trying to login using the username and password
![login](https://user-images.githubusercontent.com/82619578/124049109-6460d700-d9dd-11eb-9e9a-f57e9233e685.PNG)

**Comment by mariaderchi** [comment]
I just tested this and it worked for me (I activated the email and was able to log in). Not sure if this was on refresh.miami instead of mymiami.tech.
