### ISSUE TITLE
UI fixes to the event calendar view

### ISSUE THREAD

**Issue by alesanchezr** [refresh-miami/refresh-miami#31]
- The days of the previous month and the next one should be in a lighter color than the current month.
- The event should have a solid border and a color that make more contrast so that it is clearer which days it covers in the calendar.
- The event's name should be bolded and centered.
![User storie](https://user-images.githubusercontent.com/82070148/124048095-2fec1b80-d9db-11eb-8047-892ad3d9fdf6.png)

**Comment by dimensionmedia** [comment]
@alesanchezr can you confirm this is still true on mymiami.tech? This is what as of this morning. Notice how past days are grey and current/future days are black and the events are formatted better. Even though we might be making some tweaks, I rather this version be the version we go by if you want to update any comments.

![Screen Shot 2021-07-12 at 9 22 49 AM](https://user-images.githubusercontent.com/721134/125294961-bd404180-e2f2-11eb-9d6f-2a8591761257.png)

**Comment by dimensionmedia** [comment]
I also might need step by step or URLs if you are viewing specific calendars, etc. The above is def. different but there are many views (list, month, etc.) to view the calendar as.

**Comment by mariaderchi** [comment]
For me, I see the text of the past events in grey and the future ones in black but the difference between the two isn't that noticeable. Seeing the whole calendar in grey gives me the sense that everything is in the past. I know this is a plugin so not sure if it's possible but can we make the days in the future have a white background and the days in the past stay with a grey background? Not a dealbreaker (I'd rather focus on more important things with our limited time) but just a thought.

**Comment by dimensionmedia** [comment]
![Screen Shot 2021-07-23 at 10 31 46 AM](https://user-images.githubusercontent.com/721134/126797383-46eb070f-0ca1-4a00-a84a-1d100b90e79a.png)

@mariaderchi  let me know if that works for you.

**Comment by mariaderchi** [comment]
That works! I'll close this ticket.
