### ISSUE TITLE
News filters don't work

### ISSUE THREAD

**Issue by alesanchezr** [refresh-miami/refresh-miami#34]
**Describe the bug**
Filters on the news are not working.

**To Reproduce**
1. Go to [here](https://refresh.miami/?s=ads&keyword=ads)
2. Pick something from the dropdown filters
3. Wait for the filters to filter.

**Expected behavior**
Website should refresh and show list of events already filtered.

**Comment by mariaderchi** [comment]
David - should we just hide the filter box for now (type, topic, industry) if that is an easy thing to do? I want to make sure our news articles are properly tagged before we allow filtering so that the filters pull good results. We could leave the 'Categories' filter. Let me know your thoughts.

**Comment by mariaderchi** [comment]
Disregard - I see that the filters have been removed. Perhaps I was on a cached page before. We can close this ticket.
