### ISSUE TITLE
As a logged-in user my profile edit section should be more concise 

### ISSUE THREAD

**Issue by YodaFace** [refresh-miami/refresh-miami#38]
## User Story:
The profile edit section should be more concise, currently there are 3 different sections (Edit, Profile Photo, Cover Photo) that currently must be re-rendered to show each aspect. 

![Screen Shot 2021-07-02 at 7 31 28 PM](https://user-images.githubusercontent.com/13352282/124338291-9f454500-db6c-11eb-8740-838361a41028.png)

This section does not need to show both the "profile photo "can "cover photo:"
![Screen Shot 2021-07-02 at 7 41 36 PM](https://user-images.githubusercontent.com/13352282/124338449-ade02c00-db6d-11eb-97d6-1b7ba5f8ec1d.png)

## Acceptance Criteria:
- By moving all 3 sections under one common section it may produce a nicer format for users and take less re-rendering on the page.

**Comment by dimensionmedia** [comment]
We are limited in terms of how we can rearrange the menus thanks to the BuddyBoss framework. I did remove the profile/cover photo from the dropdown however.

![Screen Shot 2021-07-12 at 8 51 34 AM](https://user-images.githubusercontent.com/721134/125290493-5e78c900-e2ee-11eb-83b3-04b67ba092b9.png)
