### ISSUE TITLE
Event navigation arrow misplaced

### ISSUE THREAD

**Issue by marcoescmont** [refresh-miami/refresh-miami#4]
**Describe the bug**
The arrows on the event navigation are misplaced, the previous and next event.

**To Reproduce**
1. Go to Events
2. Click on First event that you see
3. Scroll down to the bottom
4. You'll see that the arrows of the previous and next event are misplaced.

**Expected behavior**
Either leave one arrow or fix the small second arrow on the button.

**Screenshots**
![Previous and next event navigation error](https://user-images.githubusercontent.com/81428361/124042802-a9820a80-d9d7-11eb-89f8-bbc2995ea61d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Google Chrome
 - Version 91.0.4472.114
 
**Smartphone (please complete the following information):**
 - Version 

**Additional context**

**Comment by dimensionmedia** [comment]
![Screen Shot 2021-07-23 at 10 12 50 AM](https://user-images.githubusercontent.com/721134/126794709-43c34354-31d5-4078-b7e8-6627e52148aa.png)

https://mymiami.tech/events/

should be resolved but @marcoescmont can you confirm and let me know what browser you are using if you are still seeing issues. thanks.
