### ISSUE TITLE
'Email Invites' appears in profile drop down, but content restricted

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#40]
I'm logged into a test account (the free tier). When I click on my name, the profile drop down has an 'Email Invites' option but when I click on it, it says 'The content you requested is restricted.'

Here's a Loom video showing it - https://www.loom.com/share/4cff99dbb2834e5f9a9dca38d5d34960

**Comment by dimensionmedia** [comment]
deactivated a plugin that might have had to do with this - restrict content for buddypress. Let's see what happens (seems to work but not sure if we stop using the plugin what might happen if anything).

**Comment by dimensionmedia** [comment]
Note that this is still accessible and working fine after i reactivated the plugin i mentioned in #36.
