### ISSUE TITLE
Job title does not appear on the job listing 

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#41]
**Describe the bug**
When I click on a specific job posting, the title of the job opening doesn't show up on the page. Perhaps this is a setting in the plugin? I believe we're having a similar issue on the current Refresh Miami site. 

**To Reproduce**
1. Go to https://mymiami.tech/jobs/
2. Click on any job listing
3. Look for the job title -- I don't see it anywhere

**Comment by dimensionmedia** [comment]
![Screen Shot 2021-07-26 at 5 02 42 PM](https://user-images.githubusercontent.com/721134/127058719-682762b7-0c0c-4fba-801e-6de01231df98.png)

resolved.
