### ISSUE TITLE
I was able to signup without accepting the terms

### ISSUE THREAD

**Issue by alesanchezr** [refresh-miami/refresh-miami#42]
When filling the [signup form](https://mymiami.tech/register/) I was able to sign up without accepting the terms.

**Comment by dimensionmedia** [comment]
![Screen Shot 2021-07-21 at 10 46 11 AM](https://user-images.githubusercontent.com/721134/126508724-33e36f2a-75bc-474d-872b-88a8d1fe9a2b.png)

Added this to be a required field.
