### ISSUE TITLE
Activation link is taking to the wrong website

### ISSUE THREAD

**Issue by alesanchezr** [refresh-miami/refresh-miami#44]
The `log in` link on [this URL](https://mymiami.tech/your-account-is-now-active/) is taking to the wrong old website.
![Screen Shot 2021-07-20 at 12 10 44 AM](https://user-images.githubusercontent.com/426452/126260753-7ad0bead-18c0-462c-a9f9-b78e26c0d871.png)

**Comment by dimensionmedia** [comment]
Resolved.
