### ISSUE TITLE
Empty sections on the profile are showing a too many comas ,

### ISSUE THREAD

**Issue by alesanchezr** [refresh-miami/refresh-miami#45]
If you log in and then got to david's profile you see a bunch of comas `,` on the side widgets:

![Screen Shot 2021-07-20 at 12 19 44 AM](https://user-images.githubusercontent.com/426452/126261429-181c0175-6e4a-4889-8eb6-b1b8be370915.png)

**Comment by dimensionmedia** [comment]
![Screen Shot 2021-07-21 at 11 54 27 AM](https://user-images.githubusercontent.com/721134/126520135-79f8f580-7cf6-4826-8a93-791240f3765e.png)
Resolved.
