### ISSUE TITLE
Company Directory & Company Pages say "Join Group"

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#47]
**Describe the bug**
When logged in and viewing the Company Directory (https://mymiami.tech/companies/) or Company Page (https://mymiami.tech/company/carecloud/), button says "Join group". Can we change this to 'Follow Company' or does Buddyboss not allow this?

**Comment by dimensionmedia** [comment]
Updated text on both urls. Might be more to update as we go through.

![Screen Shot 2021-07-25 at 6 28 49 PM](https://user-images.githubusercontent.com/721134/126915361-70e79d71-0e66-4781-be34-5f486a666794.png)

![Screen Shot 2021-07-25 at 6 29 10 PM](https://user-images.githubusercontent.com/721134/126915377-6bfe265f-df63-466f-a860-68a1e065e0a5.png)

**Comment by mariaderchi** [comment]
Thank you!
