### ISSUE TITLE
Social buttons all lead to Twitter

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#48]
**Describe the bug**
All the social buttons in the footer under "Connect Socially" lead to Twitter instead of Facebook, Youtube, Instagram, etc.

**Comment by dimensionmedia** [comment]
Update them here @mariaderchi 

https://mymiami.tech/wp-admin/widgets.php

![Screen Shot 2021-07-25 at 5 42 01 PM](https://user-images.githubusercontent.com/721134/126914340-473f722d-8355-4fdd-82e4-c2831b873970.png)

**Comment by mariaderchi** [comment]
Done - thanks!
