### ISSUE TITLE
Text in News Header unrelated to Archive search conducted

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#49]
**Describe the bug**
When you click on one of the News section

**To Reproduce**
1. Go to an individual article (https://mymiami.tech/boca-codes-diversity-scholarship-program-grows-through-partnership-with-microsoft-miami-edtech/)
2. In the right rail under 'Archies', Click on 'May 2021'
3. When that page loads, the title of an article appears in the blue bar header instead of the search topic ('May 2021') - https://mymiami.tech/2021/05/

If it makes things easier, can we just remove the 'Archives' box on the individual article page?

**Screenshots**
![Screen Shot 2021-07-20 at 2 25 45 PM](https://user-images.githubusercontent.com/87676431/126376180-e8c7baa4-e088-4d9c-bed5-11591d03d33c.png)

**Comment by dimensionmedia** [comment]
![Screen Shot 2021-07-25 at 6 12 50 PM](https://user-images.githubusercontent.com/721134/126915053-2bde41e7-8c4d-40ef-8263-0a536a36b4ff.png)

Should see something like this now?

**Comment by mariaderchi** [comment]
Hi David - It appears to be working better now but the title in the header is always one month off from the search conducted. Here is a Loom showing it - https://www.loom.com/share/2547d783d0aa4f91a5de82cec5a16324.

**Comment by dimensionmedia** [comment]
Should be resolved: https://mymiami.tech/2021/05/

**Comment by mariaderchi** [comment]
There seems to still be a major caching issue on the site. Here is a video showing what I mean - https://www.loom.com/share/0dabddbf37f5476b9c637974466eb2ca

**Comment by dimensionmedia** [comment]
Video: https://www.loom.com/share/5d03ef9ff56f4c9bb555aca0262df279

**Comment by mariaderchi** [comment]
Thanks David! I tested it and you're right - the issue doesn't seem to happen if I'm logged in. I reached out to Brian and he thinks tech support fixed it last time so we'll try that again. In the mean time, I will close this ticket.
