### ISSUE TITLE
Upcoming Events & Jobs displayed on homepage are not the same throughout the site

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#50]
**Describe the bug**
The upcoming events and jobs that show up on the right rail of the homepage, do not consistent in other areas of the site (like on the News page - https://mymiami.tech/news/). Can we make it so that they're consistent?

**Comment by dimensionmedia** [comment]
This wasn't REALLY how we discussed. Homepage was to offer more and more featured events (and jobs). Homepage has extra $$$. But I've gone ahead and invested some time and we should be seeing similar jobs/events in the sidebar on

https://mymiami.tech/news/
https://mymiami.tech/2021/05/

Hoping cache is clear so you can see these! :-)

**Comment by mariaderchi** [comment]
Thanks David! It looks good. One last request - for the events that are featured, they should always be prioritized and listed at the top of the widget however for the ones just beneath the featured ones, is it possible to list them in order of date of the event, with the event happening soonest listed directly under the featured ones?

**Comment by brianbreslin** [comment]
@dimensionmedia on that /2021/05 page I see this 
![Screen Shot 2021-07-26 at 5 02 19 PM](https://user-images.githubusercontent.com/393659/127058722-ed0f9d6c-a6f4-47f8-b35e-7f5dedd6e457.png)

**Comment by dimensionmedia** [comment]
should be updated.

![Screen Shot 2021-07-26 at 4 48 53 PM](https://user-images.githubusercontent.com/721134/127057129-eaf77b7f-65ca-4dd5-888f-1eb6461dbad2.png)

**Comment by mariaderchi** [comment]
Thanks David! Can you please reverse the order (put the event that is happening soonest at the top, just below the 'Featured' Events)?

**Comment by dimensionmedia** [comment]
![Screen Shot 2021-07-27 at 8 48 34 AM](https://user-images.githubusercontent.com/721134/127156591-3faafcd6-c5c2-4bd5-8937-ec8fb88c720c.png)

Check this.

**Comment by mariaderchi** [comment]
Thanks David! Closing this ticket.
