### ISSUE TITLE
Quality of the image in the footer is pixelated 

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#51]
**Describe the bug**
The quality of the image in the footer looks pixelated - especially compared to the Header.

**Comment by dimensionmedia** [comment]
Not seeing this. Maybe include your own screenshot @mariaderchi 

![Screen Shot 2021-07-25 at 5 40 11 PM](https://user-images.githubusercontent.com/721134/126914291-946f6084-90b6-459e-b055-faee26962333.png)

**Comment by lubryan1981** [comment]
Here is the image Maria is referring to. The source image does appear distorted. 
https://mymiami.tech/wp-content/themes/buddyboss-theme-child/assets/images/footer/footer-main.jpg
I can replace if you let me know where this is uploaded. Perhaps a footer widget?

**Comment by dimensionmedia** [comment]
Just upload via the WordPress media library and send me the url here and I’ll update the CSS (cusotm.css in the theme).

**Comment by lubryan1981** [comment]
@dimensionmedia  https://mymiami.tech/wp-content/uploads/2021/08/refresh-miami-footer-background.jpg

**Comment by dimensionmedia** [comment]
The image has been replaced. I see the color shade update on my end.
