### ISSUE TITLE
"Cannot be reported" bug on Company Page

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#52]
**Describe the bug**
When I try and report a company, I get the following error - 'Can not be reported.' (I tried under two different accounts, an admin level one and a free level account). 

Loom video - https://www.loom.com/share/63c055af5fc04f9091c3a3b97e2efd3c

**To Reproduce**
1. Go to Company Directory
2. Click on a company
3. Click on "Report Company"
4. Try to file a report
5. You will get an error saying "Can not be reported."

**Comment by dimensionmedia** [comment]
This is a bug in the plugin we are using, or at least it seems right now. I removed something form the plugin the MIGHT make this work - after some research. Let's do another test. You should see the reported item here:

https://mymiami.tech/wp-admin/admin.php?page=bpmts-moderation

You should get an email, might be coming to me. In fact re-ccheck all the settings: https://mymiami.tech/wp-admin/admin.php?page=bpmts-settings

**Comment by dimensionmedia** [comment]
![Screen Shot 2021-07-25 at 6 47 25 PM](https://user-images.githubusercontent.com/721134/126915765-d246b0d6-1b5e-4c60-be51-6678d4bddd87.png)

Evidence.

**Comment by mariaderchi** [comment]
Working now - thanks!
