### ISSUE TITLE
Homepage still says 'Create Your Profile' even though I'm logged in

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#54]
## User Story:
When I'm logged in, I noticed that the homepage still prompts me to 'Create your profile' and if I click on it, it drives me to the membership pricing page. If possible, can we update that section to says 'update your profile' if someone is logged into their account and drive them to their current profile page? Or remove the button altogether for people that are logged in?

Here's a video explaining what I mean - https://www.loom.com/share/b397b8b35e14449f81b74350d474687b

**Comment by dimensionmedia** [comment]
There's no good way to detect login/logout in the slider app. We might be able to duplicate the slider completely and switch out if the user is logged in/out. Might take a little effort though, so pushing this down priority list.

**Comment by lubryan1981** [comment]
Right, perhaps change the cTA to something like - check out events. that way it doesn't have to look at all the various profile aspects. Even is the profile is updated, what would it show then? Seems like too much logic involved.

**Comment by lubryan1981** [comment]
@dimensionmedia where do you change the homepage elements? (main header, and button). thx

**Comment by dimensionmedia** [comment]
That depends. Best user friendly area to start with would be

https://mymiami.tech/wp-admin/admin.php?page=buddyboss_theme_options <https://mymiami.tech/wp-admin/admin.php?page=buddyboss_theme_options>

Be careful!
