### ISSUE TITLE
Memberships not working

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#55]
I've signed up for various memberships but they don't appear in the back end - https://www.loom.com/share/f20a3dce2d2c4a87b8c80087a4d9117a

**Comment by brianbreslin** [comment]
are they not registering the users anywhere? I created one now. https://mymiami.tech/members/elbrian/ and went through entire process. 
We should ask for photo at some point or avatar.

**Comment by dimensionmedia** [comment]
I thought in our refresh.miami testing paid memberships work, but i'm not finding right now the "connecting tissue" between purchase via Stripe and the membership plugin. So it's possible this might need to be addressed, and if so will take some bandwidth. Surprised all the testing and testers didn't hit this though, so maybe i'm wrong.

@mariaderchi let's ensure non-membership items have been tested so we can estimate things after this particular ticket is completed. Confirm if #36 is resolved with this taking priority.

Have a good Wednesday!

**Comment by dimensionmedia** [comment]
Any possibility I can get test CC for the testing this week? My biz card was lost and unless you want to wait a week for me to get another one, I’ll need something to test. It would be $1-$4 refundable in stripe.
