### ISSUE TITLE
Paid memberships not allowing you to add an event

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#57]
I tested adding an event to the community calendar under both a Contributor-level membership (mderchitest4) and a Partner-level membership (mderchipartner) and when I try to add an event, I'm taken to the Upgrade membership page (https://mymiami.tech/upgrade/). Paid-level members should have the ability to add events. 

Also, when I go to my Membership Details page (https://mymiami.tech/members/mderchipartner/settings/account/), it shows my Partner monthly membership invoice as $3 instead of $100 (it shows up correctly as $100 in Stripe).

**Comment by dimensionmedia** [comment]
Posting an event for memberships has been revised. I can see the post page with at least one of the test users. Can you confirm?
