### ISSUE TITLE
Data captured during onboarding isn't appearing in the user profile & Members no longer showing up in Member directory

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#58]
Here is a video describing the issues: 

https://www.loom.com/share/9fd2abeb64bd483ca4ce8c685de0f515

Sorry I realize I should probably have recorded two videos and filed this under two tickets but I need to clean out my Loom account because I'm hitting my 25 limit.

**Comment by mariaderchi** [comment]
Just an update on this one - I was able to hide the "All Types" filter at the top of the Members page so don't worry about that anymore.

**Comment by dimensionmedia** [comment]
I did a test with a new user. Attached is what i entered when my user was activated and i wen through the enhancement process. Screenshot of also what tags showed up in my profile right after wards.

So some tags showed up. So I can reproduce the issue up to a point, but it's something i'll look into. I don't think software updates did this, but I'm wondering if this was tested after all the tags were refreshed/entered that one time. We'll see.

![Screen Shot 2021-08-23 at 10 00 53 AM](https://user-images.githubusercontent.com/721134/130467084-42e8857b-fe68-4384-bd89-bc55fe816909.png)
![Screen Shot 2021-08-23 at 10 01 06 AM](https://user-images.githubusercontent.com/721134/130467089-bfe93914-5e64-4d8f-b352-88122cd18793.png)
![Screen Shot 2021-08-23 at 10 39 53 AM](https://user-images.githubusercontent.com/721134/130467091-b6c12803-90e3-40db-907f-be73f36b498d.png)

**Comment by dimensionmedia** [comment]
This might be resolved. Not an issue regarding updates but you literally had to pick the wrong choices for the bug to appear I think. We should test with new and existing user (although /enhance i'm guessing is something only someone will visit once?)

![Screen Shot 2021-08-23 at 3 10 01 PM](https://user-images.githubusercontent.com/721134/130504027-cbe63439-1868-42b5-9a99-42a9ec16e33d.png)

**Comment by mariaderchi** [comment]
I did some testing and the roles and expertise appear to be saving now. However, some of the other items entered in the /enhance process like zip code and gender are not. Also, the buttons that allow you to "Join Discussions" based on the interest/roles you enter don't really do anything. I recorded a video to take you through what I mean - https://www.loom.com/share/a31a0bb980b94d11b17f0303761cda68

Lastly, for people that opt in to the talent database, where does that

**Comment by dimensionmedia** [comment]
The zip code and gender items are updated however i think there might be more here that might have missed testing. Here's a video where i attempt to explain (also trying to cover the "join discussions"):

https://www.loom.com/share/b210db05a34f4f259f1ef9fdd778c939

**Comment by lubryan1981** [comment]
I see the gender settings here that match the "edit profile" section. https://mymiami.tech/wp-admin/admin.php?page=bp-profile-setup&mode=edit_field&group_id=7&field_id=43
The onboarding form must be hardcoded?

**Comment by dimensionmedia** [comment]
The form is controlled in the back admin area. Gravity Forms makes the form. Adding fields isn’t a problem, but adding things obviously will change visuals. Just need to know what fields we do vs. don’t need (and that’s just addressing the gender settings).

**Comment by mariaderchi** [comment]
Thanks David - that video was very helpful. As I rethink the whole /enhance onboarding flow, I'm wondering if it makes sense for the time being to bypass it and drop people off on the 'Edit your profile' page, perhaps with a pop-up that explains why this should complete it ("To get the most out of your experience, take a few minutes to tell us about yourself"). Here is a video I recorded explaining what I mean - https://www.loom.com/share/de47dbba70d845dda25c0134a2a7c845. Curious if that makes things easier from a dev perspective. Thanks!

**Comment by dimensionmedia** [comment]
﻿
It might be easier, but:

It’s about what’s right and what get’s the data you want. My video wasn’t stressing on the difficultly or time, but just trying to figure out what fields sync up with what in the profiles. I think these were looked at in two different time frames (but maybe I’m wrong). Like, we don’t have address data for users. Maybe we should. Maybe they should be added? Adding them and redirecting to the profiles are ok. We can also simply remove the talent db and the discussion steps in the /enhance. You can also bug people to update their profile (we have a widget for that - its appears on profile pages).

The /enhance is pretty much there. The problem I think was we never had a sync conversation and/or fields were changed and that’s why zip code and gender broke (the tags issues was another issue, simply a “not enough testing to find the bug” problem).

**Comment by mariaderchi** [comment]
Hi David,

Just an update to my last message:

- I updated both the Gender profile options and the Gender options in the /enhance form. The 'transgender' option gets pushed to the next line. Not sure if there's a way to fix that. 
- I tried hiding the Talent Database option in the form but the step is still there. Was scared to outright delete it and break something but if you tell me it's ok, I'm happy to delete it from the form. 

Please keep me posted on the other items. I think once these are covered, I feel comfortable updating the site with whatever content was added since the last import, then launching (yay!!). Thanks!

**Comment by dimensionmedia** [comment]
![Screen Shot 2021-08-29 at 4 11 28 PM](https://user-images.githubusercontent.com/721134/131264044-cda88593-e68d-4eea-a061-08c172fae188.png)

Gender CSS updated. Working on other items and will keep you updated.

**Comment by dimensionmedia** [comment]
Maria,

Following might be updated, at least I got it working in my limited testing. You can test this now or wait until I resolve the submission/discussion issue.

- Managed to get the “Tell us what you're looking to get out of this community so we may better serve you!” To populate the profile field from the /enahnce form.
- Totals should start appearing now in the RM stats - there’s a new section for the totals under “jobs”
- Hid the talent database step in the /enhance

I’ll let you know when I can get some answers on subscribe discussions.

**Comment by mariaderchi** [comment]
Thanks David! I tested everything you mentioned and it looks to be working! One thing I noticed was that you can only see the  “Tell us what you're looking to get out of this community so we may better serve you!” responses when you edit your profile but you can't see it on your public profile page like you can see roles and expertise (see below). Is that something easy to add?

<img width="1144" alt="Screen Shot 2021-08-30 at 9 12 00 AM" src="https://user-images.githubusercontent.com/87676431/131345394-78ec177b-cf80-4887-b0b1-78f1ab82bb46.png">

**Comment by dimensionmedia** [comment]
Here's a video explaining my conclusion on subscription to forums: https://www.loom.com/share/d1d376cef52645868a4e87cba3481ce1

**Comment by mariaderchi** [comment]
Thanks David! Here is my video response - https://www.loom.com/share/a3f69c995a6f41a592fe72436f6620c6

To answer your previous question re: "tell us how the community can help you", I would like the box on the public profile to appear directly below the 'Roles' and 'Expertise' box. The title of the box should say "What (insert user first name) is looking for:" If it's not possible to insert the user name, it can say "What I'm looking for:"
 
<img width="1276" alt="Screen Shot 2021-08-31 at 8 40 15 PM" src="https://user-images.githubusercontent.com/87676431/131593551-957d5d10-ce9b-49ec-a692-72d94ad54d31.png">

**Comment by dimensionmedia** [comment]
Re: Community help. See screenshot and also https://mymiami.tech/members/dbisset/

Needs testing because I only tested my one user. Should test no values, one value, multiple values. Thanks.

![Screen Shot 2021-09-02 at 2 11 10 PM](https://user-images.githubusercontent.com/721134/131895245-0edde2ac-57f0-4ab6-b5f2-ccad1bbaec33.png)

**Comment by mariaderchi** [comment]
Tested with no values, one value and multiple values. Appears to be working well!

**Comment by dimensionmedia** [comment]
Regarding subscribe discussions: https://www.loom.com/share/257880d8c1d7484b8fb5fc22d3658241

Feel free to test.

**Comment by mariaderchi** [comment]
Thanks David! I just did some testing and it looks to be working well! As for free members versus paid members, all members are able to subscribe to discussion/forum topics and add to a discussion but only paid members can start a new discussion so I think we're all set! I will close this ticket now. Thanks!
