### ISSUE TITLE
Contact Us form isn't working

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#59]
I'm not sure what email it is setup to send to but I tested filling out the form on the Contact Us page (https://mymiami.tech/contact/) and I didn't receive an email.

**Comment by dimensionmedia** [comment]
@mariaderchi can you check this out? admin email might be mine but i haven't seen a test contact form email. But change this to your email for now and see if this works:

https://mymiami.tech/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=notification&id=12&nid=60d20aa54f78c

![Screen Shot 2021-08-20 at 10 33 40 AM](https://user-images.githubusercontent.com/721134/130249487-4efb3609-7dc3-44c9-8934-570a805d3ccf.png)

**Comment by mariaderchi** [comment]
Working now - thanks!
