### ISSUE TITLE
Updating landing pages that require a membership upgrade

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#60]
To be consistent, can we please update the following landing pages for when someone selects a feature that requires a membership upgrade:

- When a logged out person or someone with a free account clicks on "Post a Job", can you please drive them to the upgrade required page (https://mymiami.tech/upgrade/) versus the pricing page.
- When a logged out person clicks on "Members", please also drive them to the upgrade required page (https://mymiami.tech/upgrade/) versus the pricing page.
- Can we make it so that no one can see "Discussions" unless they're logged in? Basically if a logged out user clicks 'Discussions', they would be taken to the upgrade language page (https://mymiami.tech/upgrade/).

**Comment by dimensionmedia** [comment]
- "Post a Job" should redirect to /upgrade but let's test all the user levels.
- "Members" redirect updated.
- Non-logged in users who click "Discussions" should now go to https://mymiami.tech/upgrade/

**Comment by mariaderchi** [comment]
Working well - Thank you David!
