### ISSUE TITLE
Partner-level membership not able to add a job

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#61]
Similar to the issue when trying to add an event, I tested posting a job with a Partner-level membership (mderchipartner) and I'm receiving the following message:

"You have submitted the maximum number of jobs for your current membership period."

However I tested it with a Contributor-level membership (mderchitest4) and it appears to be working.

**Comment by dimensionmedia** [comment]
You need to assign job limits to memberships. Covered this in a video but i don't have time to recreate.

Go here:
https://mymiami.tech/wp-admin/admin.php?page=rcp-member-levels

Click on membership level.

Scroll to the bottom and make sure job level isn't zero. Adjust number and see if that works.

![Screen Shot 2021-08-20 at 3 01 33 PM](https://user-images.githubusercontent.com/721134/130281524-de9e9517-c74d-4965-a741-1ea671aae122.png)

**Comment by mariaderchi** [comment]
Hi David - I checked in the backend and made sure the jobs limit were 100+. It still does not allow me to add a job under both Contributor level or Partner level memberships :(

**Comment by dimensionmedia** [comment]
Give this another shot. Was able to get to page with one of your test users.

David Bisset
WordPress/PHP Developer
— davidbisset.com
— twitter.com/dimensionmedia
— linkedin.com/in/davidbisset

**Comment by mariaderchi** [comment]
Works now! Closing this ticket.
