### ISSUE TITLE
Updating the 'Activate your account' email?

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#62]
I tried updating the 'Activate your Refresh Miami account' email but I don't see where I can do this. I went to BuddyBoss --> Emails --> **[{{{site.name}}}] Activate your account** and changed the text but when I test it, I still receive the old email. I know a while back we were having an issue with the spacing of this email being off so not sure if you hardcoded it or put it somewhere else in the backend that I can't find. Thanks!

**Comment by dimensionmedia** [comment]
@mariaderchi can you see if this is what you're looking for?

https://mymiami.tech/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=notification&id=11

If not remind me and forward or paste the email here and i'll do a keyword search. There are multiple places to look and I hope this is isn't hardcoded by a plugin.

**Comment by mariaderchi** [comment]
That did the trick! The only thing I screwed up is the 'Activate URL' link. It doesn't pass through to the email.

**Comment by dimensionmedia** [comment]
Try removing the placeholder tag(s) and inserting them again in the dropdown right next to the textfield. “User Activation Link” is one of the choices. Probably have the wrong number of brackets.

David Bisset
WordPress/PHP Developer
— davidbisset.com
— twitter.com/dimensionmedia
— linkedin.com/in/davidbisset

**Comment by mariaderchi** [comment]
That worked - thanks! Closing the ticket now.
