### ISSUE TITLE
Name of membership and cost on Membership invoice

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#63]
On the Membership page, the invoice section for Partner-level memberships (in this case, for username "mderchipartner"), the invoice says "Business monthly" with a cost of $3 instead of "Refresh Miami Partner (Monthly Plan) for $100/month. 

<img width="1269" alt="Screen Shot 2021-08-20 at 10 12 43 PM" src="https://user-images.githubusercontent.com/87676431/130308295-d0a321f9-5bf6-402b-a14d-61712fa63d78.png">

**Comment by dimensionmedia** [comment]
There are endless places to replace and change when we update the names and costs of these memberships, but I think i found the final pieces. Let's do a fresh test on this.

**Comment by mariaderchi** [comment]
Just tested it with a new membership - mderchipartner2 - and it worked! Thanks David - closing this ticket now.
<img width="1238" alt="Screen Shot 2021-08-21 at 10 05 21 AM" src="https://user-images.githubusercontent.com/87676431/130324284-d658d8d4-88b2-4da8-bf0d-7913c91ca0ea.png">
