### ISSUE TITLE
Event List Page

### ISSUE THREAD

**Issue by lubryan1981** [refresh-miami/refresh-miami#68]
On Events page: https://mymiami.tech/events/
"Next Events" is not linked. 

Presumably it should go to: https://mymiami.tech/events/list/?eventDisplay=future

Keep in mind that once on future events page (link) above, the next events link goes back to the regular list, instead of future, future events, if that makes sense.

**Comment by mariaderchi** [comment]
@brianbreslin - can you please look into this since you tend to be ore familiar with the Events Calendar Pro plugin?

**Comment by brianbreslin** [comment]
@lubryan1981 i suspect this is due to there not being any events from October in there and the list is showing the 10 next events (and there are fewer than 10). I submitted a ticket anyway.

**Comment by mariaderchi** [comment]
Below is the response from the Events Calendar Pro folks. I'm scared to mess anything up so can whoever feels comfortable doing this, give it a shot? Thank you!

-------

Thanks for reaching out.

That is odd. At first I wondered if you had any events past Sept 17th, but month view shows that you clearly do have events in the future.

The link you provided that "works" doesn't really work. The button is clickable, but clicking on it just takes you to the same page you're already on, displaying the same events from Sept 1 to Sept 17th. Clicking it doesn't progress to October.

We'll start with the basics:

Please navigate to Events > Help > System Information check the box to share info and click the Copy to Clipboard button and paste the info in this chat.

1. Please try deactivating all plugins (except calendar plugins of course) and see if the issue persists

2. Please try activating a default theme, like 2020 and see if the issue persists.

**Comment by dimensionmedia** [comment]
Maria,

I duplicated production to a staging server. You can grant support access by creating an admin user if you want.

https://wordpress-605962-1962005.cloudwaysapps.com/wp-admin

I switched to a default WP theme and didn’t fix anything. I deactivated a few plugins but some of the plugins like BuddyBoss are needed to keep the site up. But the point of staging is that you can’t do any wrong, if all plugins are to be turned off, then that’s something that can be tried.

I am noticing that the Events Calendar plugins might need updates but I don’t know the first thing where to get them. Brian might know. If you have a legit license and give support admin access likely they can update them.

https://wordpress-605962-1962005.cloudwaysapps.com/wp-admin/plugins.php?plugin_status=all&paged=1&s
