### ISSUE TITLE
When Expertise & Role are left blank, Meetups are recommended

### ISSUE THREAD

**Issue by mariaderchi** [refresh-miami/refresh-miami#69]
I tested going through the /enhance onboarding and didn't select any of the expertise or role options. When I get to the part where it recommends discussion/forum topics based on roles/expertise, it serves me these old Meetup groups. Instead, it should just recommend the "Introductions" discussion/forum topic since that is relevant for all new members. 

<img width="721" alt="Screen Shot 2021-09-02 at 2 23 42 PM" src="https://user-images.githubusercontent.com/87676431/131897039-ac0551aa-7f6e-4f9f-af36-adadce5ad8b3.png">

**Comment by dimensionmedia** [comment]
![Screen Shot 2021-09-04 at 2 26 10 PM](https://user-images.githubusercontent.com/721134/132104573-2ccc7872-1596-4fb5-a78e-c5edb8007504.png)

@mariaderchi 

Without entering anything you should now see this. I tested to see if it subscribed me to introductions and it did.
We should test this AND test to make sure this didn't effect normal recommendations, although I tested that once too.

**Comment by mariaderchi** [comment]
Tested and looks to be working well! Thank you - will close this ticket!
