### ISSUE TITLE
As a member, I should see my autofilled signup bar in bold so that I know it has correctly selected my text so that I can click sign in.

### ISSUE THREAD

**Issue by brcre001** [refresh-miami/refresh-miami#7]
## User Story:
```
As a registered user, I should see my autofilled signup bar in bold so that I know it has correctly selected my text so that I can click sign in.
```
## Screenshot:
![SignInRefreshMiami](https://user-images.githubusercontent.com/83432261/124044782-3038e680-d9dc-11eb-97e5-d4e6d92bb42f.png)

## Acceptance Criteria:

Elaborate more on the story for specific expected behaviors, for example:
- The text in the username and password slot should be black and bolded when it is autofilled.
- The view icon next to the password should be centered with the text

**Comment by lubryan1981** [comment]
Not sure this is the case on miami.tech.
