### ISSUE TITLE
As a public user, I should be able to see the news title centered within the title so that the page looks aligned correctly

### ISSUE THREAD

**Issue by brcre001** [refresh-miami/refresh-miami#8]
## User Story:
```
As a public user, I should be able to see the news title centered within the title so that the page looks aligned correctly
```
## Screenshot:
![NewsTitleUncentered](https://user-images.githubusercontent.com/83432261/124046219-6deb3e80-d9df-11eb-9982-0563657b42d5.png)

## Acceptance Criteria:

Elaborate more on the story for specific expected behaviors, for example:
- The news title should be centered in the blue box

**Comment by lubryan1981** [comment]
Global element. Updated in css. 


.masthead h1 {
    color: white;
    width: 40%;
    min-width: 380px;
    padding-left: 20px;
    padding-right: 50px;
    padding-top: 35px;
